spring.application.name=workflow-app

# H2 In-Memory Database
spring.datasource.url=jdbc:h2:mem:workflowdb
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Disable open-in-view
spring.jpa.open-in-view=false

# JWT
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000
